package jetbrains.mps.samples.Physics.sandbox;

/*Generated by MPS */

import jetbrains.mps.samples.Physics.runtime.Simulation;
import jetbrains.mps.sample.Physics.runtime.objects.World;
import jetbrains.mps.sample.Physics.runtime.objects.PhysicalEntity;
import jetbrains.mps.samples.Physics.runtime.vectors.InternalVector;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.math.BigInteger;
import jetbrains.mps.sample.Physics.runtime.objects.rendering.BoxFixture;
import java.util.Arrays;
import jetbrains.mps.sample.Physics.runtime.objects.forces.Force;
import jetbrains.mps.sample.Physics.runtime.objects.forces.StaticForce;
import org.ode4j.math.DVector3C;

public class TestSimulation extends Simulation {

  @Override
  protected void init(World world) {
    PhysicalEntity Something = new PhysicalEntity(world);
    PhysicalEntity Hey = new PhysicalEntity(world);
    PhysicalEntity Ho = new PhysicalEntity(world);
    PhysicalEntity Ho1 = new PhysicalEntity(world);
    PhysicalEntity Ho2 = new PhysicalEntity(world);
    Something.getBody().setPosition(new InternalVector(((Number) new BigDecimal("24.75930987492931488653859956720080").setScale(32, RoundingMode.DOWN)), ((Number) new BigDecimal("-11.98318881128280165539097150082561").setScale(32, RoundingMode.DOWN)), ((Number) new BigDecimal("12.65667399399961978240630346190694").setScale(32, RoundingMode.DOWN))).toDVector3C());
    Something.getBody().setLinearVel(new InternalVector(((Number) new BigInteger("20")), ((Number) new BigInteger("20")), ((Number) new BigInteger("20"))).toDVector3C());
    Something.setFixture(new BoxFixture(world, 2, 2, 2), ((Number) new BigInteger("20")));
    Something.getForces().addAll(Arrays.asList(new Force[]{new StaticForce(new InternalVector(((Number) new BigInteger("2")), ((Number) new BigInteger("2")), ((Number) new BigInteger("2")))), new Force() {
      @Override
      public DVector3C getForce(World world, PhysicalEntity targetEntity) {
        return Hey.resize(((Number) new BigInteger("3"))).toDVector3C();
      }
    }, new StaticForce(InternalVector.fromSpherical(((Number) new BigDecimal("1.5707963267948966").setScale(16, RoundingMode.DOWN)), ((Number) new BigDecimal("0.001111110653864079").setScale(18, RoundingMode.DOWN)), ((Number) new BigDecimal("900.0005555553840878973394160353825").setScale(31, RoundingMode.DOWN)))), new StaticForce(new InternalVector(((Number) new BigInteger("44")), ((Number) new BigInteger("00")), ((Number) new BigInteger("4"))))}));
    Hey.getBody().setPosition(new InternalVector(((Number) new BigDecimal("27.46035823174609274397702460056475").setScale(32, RoundingMode.DOWN)), ((Number) new BigDecimal("-9.282140454466024179938468351046636").setScale(33, RoundingMode.DOWN)), ((Number) new BigDecimal("5.627543496627525070275583761154096").setScale(33, RoundingMode.DOWN))).toDVector3C());
    Hey.getBody().setLinearVel(new InternalVector(((Number) new BigInteger("9")), ((Number) new BigInteger("4")), ((Number) new BigInteger("4"))).toDVector3C());
    Hey.setFixture();
    Hey.getForces().addAll(Arrays.asList(new Force[]{}));
    Ho.getBody().setPosition(new InternalVector(((Number) new BigDecimal("-28.4603582317460934089775887225640").setScale(31, RoundingMode.DOWN)), ((Number) new BigDecimal("8.282140454466024558661369602784440").setScale(33, RoundingMode.DOWN)), ((Number) new BigDecimal("4.62754349662752150").setScale(17, RoundingMode.DOWN))).toDVector3C());
    Ho.getBody().setLinearVel(new InternalVector(((Number) new BigInteger("0")), ((Number) new BigInteger("0")), ((Number) new BigInteger("0"))).toDVector3C());
    Ho.setFixture();
    Ho.getForces().addAll(Arrays.asList(new Force[]{}));
    Ho1.getBody().setPosition(new InternalVector(((Number) new BigInteger("5")), ((Number) new BigInteger("5")), ((Number) new BigInteger("5"))).toDVector3C());
    Ho1.getBody().setLinearVel(new InternalVector(((Number) new BigDecimal("36.27019828550950343905742890562011").setScale(32, RoundingMode.DOWN)), ((Number) new BigDecimal("-19.81971846161784190496693731503488").setScale(32, RoundingMode.DOWN)), ((Number) new BigDecimal("17.79470360618654315412074105620786").setScale(32, RoundingMode.DOWN))).toDVector3C());
    Ho1.setFixture();
    Ho1.getForces().addAll(Arrays.asList(new Force[]{}));
    Ho2.getBody().setPosition(new InternalVector(((Number) new BigInteger("44")), ((Number) new BigInteger("24")), ((Number) new BigInteger("14"))).toDVector3C());
    Ho2.getBody().setLinearVel(new InternalVector(((Number) new BigDecimal("-19.65460714874940750568508553188864").setScale(32, RoundingMode.DOWN)), ((Number) new BigDecimal("-3.364135566046386756416433677680972").setScale(33, RoundingMode.DOWN)), ((Number) new BigDecimal("-1.542403877585388732131631157560971").setScale(33, RoundingMode.DOWN))).toDVector3C());
    Ho2.setFixture();
    Ho2.getForces().addAll(Arrays.asList(new Force[]{}));
  }
}
