package jetbrains.mps.samples.Physics.sandbox;

/*Generated by MPS */

import jetbrains.mps.samples.Physics.java.runtime.objects.SystemScope;
import jetbrains.mps.samples.Physics.java.runtime.objects.forces.Force;
import org.ode4j.math.DVector3C;
import jetbrains.mps.samples.Physics.java.runtime.objects.World;
import jetbrains.mps.samples.Physics.java.runtime.objects.PhysicalEntity;
import jetbrains.mps.samples.Physics.java.runtime.VectorHelper;
import jetbrains.mps.samples.Physics.java.common.vectors.InternalVector;

public class XYZForceForce<T extends SystemScope> implements Force<T> {
  private Number x;
  private Number y;
  private Number z;

  public XYZForceForce(Number x1, Number y1, Number z1) {
    this.x = x1;
    this.y = y1;
    this.z = z1;
  }

  @Override
  public DVector3C compute(World world, T scope, PhysicalEntity currentEntity, double time) {

    return VectorHelper.fromInternal(new InternalVector(x, y, z));
  }
}
