package jetbrains.mps.samples.Physics.java.runtime;

/*Generated by MPS */

import com.badlogic.gdx.graphics.g3d.Environment;
import com.badlogic.gdx.graphics.g3d.ModelBatch;
import jetbrains.mps.samples.Physics.java.common.vectors.VectorLike;

public interface Renderable {
  default void setup(Environment env, float scale) {
  }
  void render(ModelBatch modelBatch, Environment env, float scale, VectorLike scaledOffset);
}
