package jetbrains.mps.samples.Physics.sample;

/*Generated by MPS */

import jetbrains.mps.samples.Physics.runtime.objects.SystemScope;
import jetbrains.mps.samples.Physics.runtime.objects.PhysicalEntity;
import jetbrains.mps.samples.Physics.runtime.objects.World;
import java.util.Arrays;
import java.math.BigInteger;

public abstract class PlanetAbstractEntity<T extends SystemScope> extends PhysicalEntity<T> {

  public PlanetAbstractEntity(World world) {
    super(world);
  }


  @Override
  public void init(T scope, World world) {
    super.init(scope, world);

    // Escape this for nested forces 
    PlanetAbstractEntity currentEntity = this;

    // Apply visual (mass of one, should be defined later) 

    // Forces 
    this.getForces().addAll(Arrays.asList(new GravityForce(((Number) new BigInteger("10")))));
  }
}
