package jetbrains.mps.samples.Physics.runtime.objects;

/*Generated by MPS */


public class EmptyParentEntity implements ParentPhysicalEntity {
  @Override
  public void applyOn(World world, PhysicalEntity target) {
    // quite unlucky for this physical entity 
  }
}
