package jetbrains.mps.samples.Physics.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.DefaultExtensionDescriptor;
import java.util.Arrays;

public class ExtensionDescriptor extends DefaultExtensionDescriptor {
  public ExtensionDescriptor() {
    super(null, Arrays.asList(new VectorInterpreter_extension()));
  }
}
