package jetbrains.mps.samples.Physics.runtime.objects.rendering;

/*Generated by MPS */

import processing.core.PApplet;

public class Color {
  public final int red;
  public final int green;
  public final int blue;

  public Color(int red, int green, int blue) {
    this.blue = blue;
    this.green = green;
    this.red = red;
  }

  public void apply(PApplet ctx) {
    ctx.noStroke();
    ctx.fill(red, green, blue);
  }
}
